// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/Animation.vue')['default']
    Assets: typeof import('./src/components/Assets.vue')['default']
    ConnectWallet: typeof import('./src/components/ConnectWallet.vue')['default']
    copy: typeof import('./src/components/WalletModal copy.vue')['default']
    CreateOrderModal: typeof import('./src/components/CreateOrderModal.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogDeposit: typeof import('./src/components/modal/DialogDeposit.vue')['default']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogStorage: typeof import('./src/components/modal/DialogStorage.vue')['default']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    DialogWithdraw: typeof import('./src/components/modal/DialogWithdraw.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    FarmDisclosure: typeof import('./src/components/FarmDisclosure.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    KLineWidget: typeof import('./src/components/KLineWidget.vue')['default']
    MarketHistory: typeof import('./src/components/MarketHistory.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OrderBook: typeof import('./src/components/OrderBook.vue')['default']
    RangeSlider: typeof import('./src/components/RangeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TradeBar: typeof import('./src/components/TradeBar.vue')['default']
    TradeFooter: typeof import('./src/components/footer/TradeFooter.vue')['default']
    TradeFrom: typeof import('./src/components/TradeFrom.vue')['default']
    TradingView: typeof import('./src/components/TradingView.vue')['default']
    TradingViewBinance: typeof import('./src/components/TradingViewBinance.vue')['default']
    TradingViewEmpty: typeof import('./src/components/TradingViewEmpty.vue')['default']
    TradingViewPlot: typeof import('./src/components/TradingViewPlot.vue')['default']
    TradingViewSimple: typeof import('./src/components/TradingViewSimple.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    UserTrade: typeof import('./src/components/UserTrade.vue')['default']
    Volume: typeof import('./src/components/Volume.vue')['default']
    WalletModal: typeof import('./src/components/WalletModal.vue')['default']
    WithdrawDropdown: typeof import('./src/components/modal/WithdrawDropdown.vue')['default']
  }
}
